Repository AY1920S1-CS2103T-F13-3/main, pull requests merged in 2019-10, with the labels that each got.

#81 Updated find command to accept multiple arguments
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/moneygowhere/commons/core/Messages.java
  src/main/java/seedu/moneygowhere/commons/util/DateUtil.java
  src/main/java/seedu/moneygowhere/logic/commands/FindCommand.java
  src/main/java/seedu/moneygowhere/logic/parser/FindCommandParser.java
  src/main/java/seedu/moneygowhere/logic/parser/ParserUtil.java
  src/main/java/seedu/moneygowhere/model/spending/Cost.java
  src/main/java/seedu/moneygowhere/model/spending/CostInRangePredicate.java
  src/main/java/seedu/moneygowhere/model/spending/Date.java
  src/main/java/seedu/moneygowhere/model/spending/DateInRangePredicate.java
  src/main/java/seedu/moneygowhere/model/spending/Name.java
  src/main/java/seedu/moneygowhere/model/spending/NameContainsKeywordsPredicate.java
  src/main/java/seedu/moneygowhere/model/spending/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/moneygowhere/model/spending/Spending.java
  src/main/java/seedu/moneygowhere/model/tag/TagPredicate.java
  src/test/java/seedu/moneygowhere/commons/util/DateUtilTest.java
  src/test/java/seedu/moneygowhere/logic/commands/FindCommandTest.java
  src/test/java/seedu/moneygowhere/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/moneygowhere/logic/parser/ParserUtilTest.java
  src/test/java/seedu/moneygowhere/logic/parser/SpendingBookParserTest.java
  src/test/java/seedu/moneygowhere/model/spending/CostInRangePredicateTest.java
  src/test/java/seedu/moneygowhere/model/spending/DateInRangePredicateTest.java
  src/test/java/seedu/moneygowhere/model/spending/DateTest.java
  src/test/java/seedu/moneygowhere/model/spending/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/moneygowhere/model/spending/RemarkContainsKeywordsPredicateTest.java
  src/test/java/seedu/moneygowhere/model/tag/TagPredicateTest.java
Labels: priority.High

#87 Implemented import command and allow duplicate spending
  build.gradle
  src/main/java/seedu/moneygowhere/logic/commands/AddCommand.java
  src/main/java/seedu/moneygowhere/logic/commands/EditCommand.java
  src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java
  src/main/java/seedu/moneygowhere/logic/parser/AddCommandParser.java
  src/main/java/seedu/moneygowhere/logic/parser/CliSyntax.java
  src/main/java/seedu/moneygowhere/logic/parser/ImportCommandParser.java
  src/main/java/seedu/moneygowhere/logic/parser/ParserUtil.java
  src/main/java/seedu/moneygowhere/logic/parser/SpendingBookParser.java
  src/main/java/seedu/moneygowhere/model/SpendingBook.java
  src/main/java/seedu/moneygowhere/model/path/FilePath.java
  src/main/java/seedu/moneygowhere/model/spending/Name.java
  src/main/java/seedu/moneygowhere/model/spending/Spending.java
  src/main/java/seedu/moneygowhere/model/spending/SpendingList.java
  src/main/java/seedu/moneygowhere/model/spending/exceptions/DuplicateSpendingException.java
  src/main/java/seedu/moneygowhere/storage/JsonSerializableSpendingBook.java
  src/test/data/JsonSerializableSpendingBookTest/duplicateSpendingBook.json
  src/test/data/SampleSpendings/invalidDateSpending.csv
  src/test/data/SampleSpendings/invalidNameSpending.csv
  src/test/data/SampleSpendings/validSpending.csv
  src/test/java/seedu/moneygowhere/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/moneygowhere/logic/commands/AddCommandTest.java
  src/test/java/seedu/moneygowhere/logic/commands/EditCommandTest.java
  src/test/java/seedu/moneygowhere/logic/commands/ImportCommandTest.java
  src/test/java/seedu/moneygowhere/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/moneygowhere/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/moneygowhere/logic/parser/SpendingBookParserTest.java
  src/test/java/seedu/moneygowhere/model/AddressBookTest.java
  src/test/java/seedu/moneygowhere/model/path/FilePathTest.java
  src/test/java/seedu/moneygowhere/model/spending/SpendingListTest.java
  src/test/java/seedu/moneygowhere/model/spending/UniqueSpendingListTest.java
  src/test/java/seedu/moneygowhere/storage/JsonSerializableSpendingBookTest.java
Labels: status.Ongoing

#85 Fix docs and bugs in find command
  docs/UserGuide.adoc
  src/main/java/seedu/moneygowhere/logic/parser/FindCommandParser.java
  src/test/java/seedu/moneygowhere/logic/parser/FindCommandParserTest.java
Labels: documentation

#95 added commands for reminders in UG and amended DG for MoneyGoWhere
  AddReminderActivityDiagram.png
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddReminderActivityDiagram.puml
  docs/diagrams/AddReminderSequenceDiagram.puml
  docs/diagrams/DeleteReminderActivityDiagram.puml
  docs/diagrams/DeleteReminderSequenceDiagram.puml
  docs/images/AddReminderActivityDiagram.png
  docs/images/AddReminderSequenceDiagram.png
  docs/images/DeleteReminderActivityDiagram.png
  docs/images/DeleteReminderSequenceDiagram.png
Labels: documentation

#98 Update DG to include Import feature
  docs/DeveloperGuide.adoc
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/images/import/ImportActivityDiagram.png
  docs/images/import/ImportSequenceDiagram.png
Labels: documentation

#80 update user guide with budget
  docs/UserGuide.adoc
Labels: documentation
